chore: Update denops/test module version
This fixes the following connection failure between deno and vim while
tests.

```
error: Error: [denops-test] Connection failed.
      throw new Error("[denops-test] Connection failed.", { cause });
            ^
    at getConn (https://jsr.io/@denops/test/2.0.1/with.ts:97:13)
    at eventLoopTick (ext:core/01_core.js:207:9)
    at async perform (https://jsr.io/@denops/test/2.0.1/with.ts:136:18)
    at async withDenops (https://jsr.io/@denops/test/2.0.1/with.ts:156:3)
Caused by: DeadlineError: Deadline
    at https://jsr.io/@std/async/0.224.0/deadline.ts:60:32
    at eventLoopTick (ext:core/01_core.js:207:9)
    at async getConn (https://jsr.io/@denops/test/2.0.1/with.ts:95:14)
    at async perform (https://jsr.io/@denops/test/2.0.1/with.ts:136:18)
    at async withDenops (https://jsr.io/@denops/test/2.0.1/with.ts:156:3)
```